/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    'BUComponentCardHubProduct copy': typeof import('./components/BUComponentCardHubProduct copy.vue')['default']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    CompDatePicker: typeof import('./components/compDatePicker.vue')['default']
    CompForm: typeof import('./components/compForm.vue')['default']
    ComponentCalendar: typeof import('./components/ComponentCalendar.vue')['default']
    ComponentCard: typeof import('./components/ComponentCard.vue')['default']
    ComponentCardHubProduct: typeof import('./components/ComponentCardHubProduct.vue')['default']
    ComponentCardStats: typeof import('./components/ComponentCardStats.vue')['default']
    ComponentCheckbox: typeof import('./components/ComponentCheckbox.vue')['default']
    ComponentDatePicker: typeof import('./components/ComponentDatePicker.vue')['default']
    ComponentImport: typeof import('./components/ComponentsImport.vue')['default']
    ComponentMapTools: typeof import('./components/ComponentMapTools.vue')['default']
    ComponentNavDrawer: typeof import('./components/ComponentNavDrawer.vue')['default']
    ComponentRadioButton: typeof import('./components/ComponentRadioButton.vue')['default']
    Components: typeof import('./components/Comp./components/ComponentSpeedDial.vue') ['default']
    ComponentsImport: typeof import('./components/ComponentsImport.vue')['default']
    ComponentSpeedDial: typeof import('./components/ComponentSpeedDial.vue')['default']
    ComponentVarious: typeof import('./components/ComponentVarious.vue')['default']
    copy: typeof import('./components/-template copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAvatarAndDropdown: typeof import('./components/tableAvatarAndDropdown.vue')['default']
    Template: typeof import('./components/-template.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
