/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/accordion': RouteRecordInfo<'/accordion', '/accordion', Record<never, never>, Record<never, never>>,
    '/card': RouteRecordInfo<'/card', '/card', Record<never, never>, Record<never, never>>,
    '/cardhubproduct': RouteRecordInfo<'/cardhubproduct', '/cardhubproduct', Record<never, never>, Record<never, never>>,
    '/cardmonitoring': RouteRecordInfo<'/cardmonitoring', '/cardmonitoring', Record<never, never>, Record<never, never>>,
    '/cardstats': RouteRecordInfo<'/cardstats', '/cardstats', Record<never, never>, Record<never, never>>,
    '/checkbox': RouteRecordInfo<'/checkbox', '/checkbox', Record<never, never>, Record<never, never>>,
    '/codebox': RouteRecordInfo<'/codebox', '/codebox', Record<never, never>, Record<never, never>>,
    '/colorramps': RouteRecordInfo<'/colorramps', '/colorramps', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/datepicker': RouteRecordInfo<'/datepicker', '/datepicker', Record<never, never>, Record<never, never>>,
    '/figmaEmbeds': RouteRecordInfo<'/figmaEmbeds', '/figmaEmbeds', Record<never, never>, Record<never, never>>,
    '/form': RouteRecordInfo<'/form', '/form', Record<never, never>, Record<never, never>>,
    '/homepage': RouteRecordInfo<'/homepage', '/homepage', Record<never, never>, Record<never, never>>,
    '/import': RouteRecordInfo<'/import', '/import', Record<never, never>, Record<never, never>>,
    '/index copy': RouteRecordInfo<'/index copy', '/index copy', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/maptools': RouteRecordInfo<'/maptools', '/maptools', Record<never, never>, Record<never, never>>,
    '/movies': RouteRecordInfo<'/movies', '/movies', Record<never, never>, Record<never, never>>,
    '/navdrawer': RouteRecordInfo<'/navdrawer', '/navdrawer', Record<never, never>, Record<never, never>>,
    '/radiobutton': RouteRecordInfo<'/radiobutton', '/radiobutton', Record<never, never>, Record<never, never>>,
    '/recordingmovies': RouteRecordInfo<'/recordingmovies', '/recordingmovies', Record<never, never>, Record<never, never>>,
    '/sidebar': RouteRecordInfo<'/sidebar', '/sidebar', Record<never, never>, Record<never, never>>,
    '/table': RouteRecordInfo<'/table', '/table', Record<never, never>, Record<never, never>>,
    '/template': RouteRecordInfo<'/template', '/template', Record<never, never>, Record<never, never>>,
    '/various': RouteRecordInfo<'/various', '/various', Record<never, never>, Record<never, never>>,
  }
}
